export const texts = {
  appTitle: 'Quiz',
  selectCertification: 'Choose your certification',
  emptyStateBefore: 'No certification bundles loaded. Valid bundles placed in',
  emptyStateHighlight: 'src/assets/',
  emptyStateAfter: 'are discovered automatically at build time.',
  questionBankLabel: 'Question bank',
  realExamLabel: 'Real exam',
  realExamValue: (count: number) => `${count} question${count === 1 ? '' : 's'}`,
  timeLimitLabel: 'Time limit',
  timeLimitValue: (minutes: number) => `${minutes} minute${minutes === 1 ? '' : 's'}`,
  passingScoreLabel: 'Passing score',
  startQuizCta: 'Start new quiz →',
  viewDashboardCta: 'View dashboard →',
  requestNoticeBefore: 'Missing a certification? There is no in-app upload —',
  requestNoticeLink: 'open a GitHub issue',
  requestNoticeAfter: 'to request it as a new built-in bundle.',
  modeLabel: 'Mode',
  modePreparation: 'Preparation',
  modeExam: 'Exam',
  replayLabel: 'Replay mode',
  replayAll: 'All questions',
  replayWrong: 'I got wrong',
  replayFlagged: 'Flagged',
  replayUnattempted: 'Unattempted',
  countLabel: 'Number of questions',
  countAll: (n: number) => `All matching (${n})`,
  countCustomLabel: 'Custom count',
  includeLabel: 'Include themes',
  excludeLabel: 'Exclude themes',
  topicsLabel: 'Topics',
  topicsAllOption: 'All',
  matchTagsLabel: 'Match tags',
  matchGroupsLabel: 'Match groups',
  quickSetupLabel: 'Quick setup',
  filterQuestionsLabel: 'Filter questions',
  matchAny: 'Match any',
  matchAll: 'Match all',
  matchAnyGroups: 'Match any group',
  matchAllGroups: 'Match all groups',
  matchingCountValue: (n: number) => `${n} question${n === 1 ? '' : 's'} match your filters`,
  noMatchWarning: 'No question matches your filters — widen them.',
  themeToggle: (dark: boolean) => (dark ? 'Switch to light mode' : 'Switch to dark mode'),
  questionOf: (n: number, total: number) => `Question ${n} of ${total}`,
  previous: 'Previous',
  next: 'Next',
  finish: 'Finish quiz',
  flag: 'Flag for review',
  unflag: 'Remove flag',
  flagged: 'Flagged',
  correct: 'Correct',
  incorrect: 'Incorrect',
  explanation: 'Explanation',
  topic: 'Topic',
  yourAnswer: 'Your answer',
  correctAnswer: 'Correct answer',
  noAnswer: 'No answer selected',
  timeUp: 'Time is up',
  submit: 'Submit answer',
  reviewTitle: 'Quiz review',
  passed: 'Passed',
  failed: 'Did not pass',
  correctCount: (n: number, total: number) => `${n} of ${total} correct`,
  projectedScaledScore: (score: number, scale: number) => `Projected scaled score: ${score} / ${scale}`,
  scaledScoreDisclaimer: 'This projected score is a linear projection and does not reflect the official certification scoring algorithm.',
  scoreBreakdownByTopic: 'Score by topic',
  scoreBreakdownByTheme: 'Score by theme',
  selectQuestionHint: 'Select a question to review its details.',
  themeGroupDisplay: (groupLabel: string, values: string[]) => `${groupLabel}: ${values.join(', ')}`,
  backToHomeCta: '← Back to home',
  backToDashboardCta: '← Back to dashboard',
  allTimeScore: 'All-time score',
  quizzesTaken: 'Quizzes taken',
  overallAccuracy: 'Overall accuracy',
  correctAnswers: 'Correct answers',
  quizHistory: 'Quiz history',
  noQuizzesTaken: 'No quizzes taken yet.',
  review: 'Review',
  delete: 'Delete',
  deleteQuizTitle: 'Delete quiz',
  deleteQuizMessage: 'Are you sure you want to delete this quiz from your history?',
  resetAllTitle: 'Reset all progress',
  resetAllMessage: 'This will delete all quiz history and reset per-question progress for this certification. This cannot be undone.',
  resetAll: 'Reset all',
  cancel: 'Cancel',
  quizNotFoundTitle: 'Quiz not found',
  quizNotFoundMessage: 'This quiz is no longer in your history. It may have been deleted or reset.',
  noQuestionsFoundMessage: 'No questions found for this topic or theme.',
  topicReviewTitle: (topic: string) => `Topic: ${topic}`,
  themeReviewTitle: (theme: string, value: string) => `${theme}: ${value}`,
  questionsForTopic: (topic: string) => `Questions for topic "${topic}"`,
  questionsForTheme: (value: string) => `Questions for theme "${value}"`,
  goBackToDashboard: 'Go back to dashboard',
}
