export const texts = {
  appTitle: 'Quiz',
  selectCertification: 'Choose your certification',
  emptyStateBefore: 'No certification bundles loaded. Valid bundles placed in',
  emptyStateHighlight: 'src/assets/',
  emptyStateAfter: 'are discovered automatically at build time.',
  questionBankLabel: 'Question bank',
  realExamLabel: 'Real exam',
  realExamValue: (count: number) => `${count} question${count === 1 ? '' : 's'}`,
  timeLimitLabel: 'Time limit',
  timeLimitValue: (minutes: number) => `${minutes} minute${minutes === 1 ? '' : 's'}`,
  passingScoreLabel: 'Passing score',
  startQuizCta: 'Start quiz →',
  requestNoticeBefore: 'Missing a certification? There is no in-app upload —',
  requestNoticeLink: 'open a GitHub issue',
  requestNoticeAfter: 'to request it as a new built-in bundle.',
  modeLabel: 'Mode',
  modePreparation: 'Preparation',
  modeExam: 'Exam',
  replayLabel: 'Replay mode',
  replayAll: 'All questions',
  replayWrong: 'I got wrong',
  replayFlagged: 'Flagged',
  replayUnattempted: 'Unattempted',
  countLabel: 'Number of questions',
  countAll: (n: number) => `All matching (${n})`,
  countCustomLabel: 'Custom count',
  includeLabel: 'Include themes',
  excludeLabel: 'Exclude themes',
  topicsLabel: 'Topics',
  topicsAllOption: 'All',
  matchTagsLabel: 'Match tags',
  matchGroupsLabel: 'Match groups',
  quickSetupLabel: 'Quick setup',
  filterQuestionsLabel: 'Filter questions',
  matchAny: 'Match any',
  matchAll: 'Match all',
  matchAnyGroups: 'Match any group',
  matchAllGroups: 'Match all groups',
  services: 'Services',
  concepts: 'Concepts',
  questionTypes: 'Question types',
  matchingCountValue: (n: number) => `${n} question${n === 1 ? '' : 's'} match your filters`,
  noMatchWarning: 'No question matches your filters — widen them.',
  themeToggle: (dark: boolean) => (dark ? 'Switch to light mode' : 'Switch to dark mode'),
}
